### ISSUE TITLE
Is the bot under maintenance?

### ISSUE THREAD

**Issue by valerionew** [MarcoPereira27/pomodore-discord-bot#6]
Second time in a row the bot today disconnects from the channel and forgets about the timer.

Is it a bug or it's just under maintenance?

**Comment by MarcoPereira27** [comment]
Hello! The bot is currently facing some connectivity issues due to a memory leak described in issue #4 and sometimes it goes offline, I'm currently working on a fix. If you have any more questions feel free to join the [Pomodore Discord Server](https://discord.com/invite/UqrA9nusjd) and I'll be happy to answer them!
